name: story_progress_indicator
description: >
  A zero-dependency Flutter package providing a Stories-style segmented progress
  indicator. Highly customizable, responsive, and driven by a single progress
  value for use with PageView, timed stories, or swipeable content.
version: 1.1.1
homepage: https://github.com/qasimerror404/story_progress_indicator
repository: https://github.com/qasimerror404/story_progress_indicator
issue_tracker: https://github.com/qasimerror404/story_progress_indicator/issues
topics:
  - stories
  - indicator
  - progress
  - animation
  - ui

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
